/* Database schema to keep the structure of entire database. */


CREATE TABLE animals (
    ID INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    date_of_birth DATE,
    escape_attempts INT,
    neutered BOOLEAN,
    weight_kg DECIMAL(10, 2)
);

ALTER TABLE animals
ADD COLUMN species VARCHAR(100);

CREATE TABLE owners (
    ID INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    full_name VARCHAR(100) NOT NULL,
    age INT
);

CREATE TABLE species (
    ID INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL
);

ALTER TABLE animals
DROP COLUMN species;

ALTER TABLE animals 
    ADD COLUMN species_id INT,
    ADD CONSTRAINT fk_species
        FOREIGN KEY (species_id) REFERENCES species(id);
		
		ALTER TABLE animals 
    ADD COLUMN owner_id INT,
    ADD CONSTRAINT fk_owners
        FOREIGN KEY (owner_id) REFERENCES owners(id);  
